
DEFAULT_SERVER_IP        = "192.168.0.101"
DEFAULT_SERVER_PORT      = 8888

DEFAULT_MALWARE_PATH     = "C:\\Windows\\System32\\NewtonRAT"
DEFAULT_MALWARE_FILENAME = "malware"
DEFAULT_REG_KEY          = "SOFTWARE\\MALWARE"

DEFAULT_CONFIG           = ""
